name: control_do_dinheiro
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  flutter_bloc: ^6.0.6
  google_fonts: any
  image_picker: ^0.6.7+12
  intl: any
  mockito: any
  shared_preferences: any
  sqflite: any
  rive: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
